### ISSUE TITLE
type "geometry" does not exist

### ISSUE THREAD

**Issue by barbozasantoz** [zonkyio/embedded-postgres#29]
> Caused by: liquibase.exception.DatabaseException: ERROR: type "geometry" does not exist
  Posição: 42 [Failed SQL: ALTER TABLE cipi.coordenada ADD location GEOMETRY]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)

The geometry type is not being recognized.
How can I configure postgis?

**Comment by tomix26** [comment]
The postgis extension is not supported yet. You can use the [testcontainers](https://www.testcontainers.org/modules/databases/postgres/) project instead. Or, if you are using [embedded-database-spring-test](https://github.com/zonkyio/embedded-database-spring-test) library, you can use the [docker provider](https://github.com/zonkyio/embedded-database-spring-test#using-docker-provider) provider.

**Comment by lukaswelte** [comment]
Postgis would be incredible to have 👍
